jobs:
  build:
    docker:
          - image: buildpack-deps:trusty # primary container
dependencies:
    override:
        - docker info
        - sudo pip install awscli
test:
    override:
        - echo "hello world"

