jobs:
  build:
    docker:
           - image:Tomcat
        #  - image: buildpack-deps:trusty # primary container
dependencies:
    override:
        - sudo pip install awscli
test:
    override:
        - echo "hello world"

