jobs:
  build:
    docker:
           - image:Tomcat
        #  - image: buildpack-deps:trusty # primary containe
         working_directory: ~/
         steps:
        - run 
            name: Running tests
            command: echo hello worlds
dependencies:
    override:
        - sudo pip install awscli
test:
    override:
        - echo "hello world"

